package com.urssu.bum.incubating.model.user

enum class PermissionType(name: String) {
    READ_MY_MEMO("READ_MY_MEMO"),
    READ_ANY_MEMO("READ_ANY_MEMO"),
    WRITE_MEMO("WRITE_MEMO"),
    MODIFY_MY_MEMO("MODIFY_MY_MEMO"),
    MODIFY_ANY_MEMO("MODIFY_ANY_MEMO"),
    DELETE_MY_MEMO("DELETE_MY_MEMO"),
    DELETE_ANY_MEMO("DELETE_ANY_MEMO"),
    READ_MY_USER("READ_MY_USER"),
    READ_ANY_USER("READ_ANY_USER"),
    MODIFY_MY_USER("MODIFY_MY_USER"),
    MODIFY_ANY_USER("MODIFY_ANY_USER"),
    DELETE_MY_USER("DELETE_MY_USER"),
    DELETE_ANY_USER("DELETE_ANY_USER")
}